name: 🐞 Bug Report
description: File a bug report
title: '[Bug]: <title>'
labels: [bug]
body:
  - type: input
    id: environment
    attributes:
      label: In which environment(s) did you encounter the bug?
      description: dev, prod, etc.
      placeholder: prod
    validations:
      required: true
  - type: input
    id: context
    attributes:
      label: Provide the context (team, organisation, etc.)
      description: The ID (or name) of the team(s) or organisation(s) affected by the bug.
      placeholder: idea
    validations:
      required: true
  - type: textarea
    id: anomaly
    attributes:
      label: Describe the anomaly
      description: Describe the feature, how the bug affects it, and how to trigger the bug.
      placeholder: 'Example: In the dashboard, I should be able to assign a user to an activity, but when I press the button ABC, I receive the error XYZ.'
    validations:
      required: true
  - type: textarea
    id: media
    attributes:
      label: Add videos and pictures
      description: Add any media to help explain the bug and how to trigger it step-by-step.
      placeholder: 'Drag and drop images and videos here'
  - type: markdown
    attributes:
      value: |
        ---
        _Please note: all fields are necessary to help the developer understand and replicate the bug; **any incomplete Issue will be marked invalid and not processed**._
